---
- name: checks if resolver is working properly (issues with some VBox/Host OS combinations)
  command: host -t A ansible.cc
  register: ns
  ignore_errors: yes

- name: pushes new resolver configuration is resolver fails
  lineinfile: regexp="^nameserver " line="nameserver 8.8.8.8" dest=/etc/resolv.conf
  sudo: yes
  when: ns|failed

- name: checks if resolver is working properly with new nameserver
  command: host -t A ansible.cc

- name: make sure the system encoding is {{ locale }}
  sudo: yes
  template: src=locale dest=/etc/default/locale
            owner=root group=root mode=644

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: install {{ item }} pkgs
  apt: pkg={{ item }}
  with_items: packages
  sudo: yes

- name: create users
  user: name={{ item.name }} home={{ item.home }}
        comment="{{ item.comment }}" generate_ssh_key=yes
        state=present
  sudo: yes
  with_items: users

- name: update access to users directory
  file: state=directory mode=755 owner={{ item.name }} group={{ item.name }} name={{ item.home }}
  sudo: true
  with_items: users

- name: update users groups
  user: name={{ item.name }} groups={{ item.groups }}
  sudo: yes
  with_items: users

- name: app_prepare | Create apps users path
  file: state=directory path={{ projects_directory }}
  sudo: yes
